/**
 * This class is generated by jOOQ
 */
package jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in library
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table library.author
	 */
	public static final jooq.tables.Author AUTHOR = jooq.tables.Author.AUTHOR;
}
