/**
 * This class is generated by jOOQ
 */
package jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorDao extends org.jooq.impl.DAOImpl<jooq.tables.records.AuthorRecord, jooq.tables.pojos.Author, java.lang.Integer> {

	/**
	 * Create a new AuthorDao without any configuration
	 */
	public AuthorDao() {
		super(jooq.tables.Author.AUTHOR, jooq.tables.pojos.Author.class);
	}

	/**
	 * Create a new AuthorDao with an attached configuration
	 */
	public AuthorDao(org.jooq.Configuration configuration) {
		super(jooq.tables.Author.AUTHOR, jooq.tables.pojos.Author.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(jooq.tables.pojos.Author object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<jooq.tables.pojos.Author> fetchById(java.lang.Integer... values) {
		return fetch(jooq.tables.Author.AUTHOR.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public jooq.tables.pojos.Author fetchOneById(java.lang.Integer value) {
		return fetchOne(jooq.tables.Author.AUTHOR.ID, value);
	}

	/**
	 * Fetch records that have <code>first_name IN (values)</code>
	 */
	public java.util.List<jooq.tables.pojos.Author> fetchByFirstName(java.lang.String... values) {
		return fetch(jooq.tables.Author.AUTHOR.FIRST_NAME, values);
	}

	/**
	 * Fetch records that have <code>last_name IN (values)</code>
	 */
	public java.util.List<jooq.tables.pojos.Author> fetchByLastName(java.lang.String... values) {
		return fetch(jooq.tables.Author.AUTHOR.LAST_NAME, values);
	}
}
